#!/bin/bash

set -e
set -u
if [[ $# -eq 1 ]]
then
    cd *"$1"*
    pwd
    ls --classify --color=always
fi

VIDEO="$(find . -iname '*avi' -o -iname '*mp4')"
AUDIO="$(find . -iname '*ac3' -o -iname '*m4a' -o -iname '*mp3')"

echo "video = $VIDEO"
echo "audio = $AUDIO"

vlc "$VIDEO" --input-slave "$AUDIO" --audio-track=1 --fullscreen --deinterlace=1

