#!/bin/bash

less_file () {
    if test $FOUND = false && test -r "$1" # file exists and is readable
    then
        FOUND=true
        less "$1"
    fi
}
FOUND=false

less_file 'README.md'
less_file 'README'
less_file 'readme.md'
less_file 'README.txt'
less_file 'readme.txt'

if test $FOUND = false
then
    echo 'No readme file found'
fi
