#!/bin/sh

less_file () {
    if ! $FOUND && test -r "$1" # file exists and is readable
    then
        FOUND=true
        less "$1"
    fi
}
FOUND=false

less_file 'README.md'
less_file 'README'
less_file 'readme.md'
less_file 'README.txt'
less_file 'readme.txt'

if ! $FOUND
then
    echo 'No readme file found'
fi
