#!/bin/bash

function usage {
    echo "Usage"
    echo "$0 HOURS [MINUTES [SECONDS]]"
    echo -e "\tTime should be specified using syntax of sleep command."
    echo ""
}

function create_list {
    find "${MUSIC}" -type f > "${LIST}"
}
function sound_alarm {
    echo "Playing sound alarm!"
    mplayer -shuffle -volume 75 -playlist "${LIST}"
    #mplayer -volume 75 -loop 0 "$HOME/music/"*
}

if [ $# -lt 1 ]; then
    usage
    exit
fi

MUSIC="/media/DATA/MUSIC/"
LIST="${HOME}/tmp/timer-music-list"

if [[ ! -r "${LIST}" ]]; then
    echo "No list found. Creating list..."
    create_list
fi

LIST_DATE="$(stat --format="%Y" ${LIST})"
CUR_DATE="$(date +"%s")"
let DIF=${CUR_DATE}-${LIST_DATE}

WEEK_IN_SECONDS=604800
if [[ ${DIF} -gt ${WEEK_IN_SECONDS} ]]; then
    echo "Updating list ..."
    create_list
fi

echo -n "Started : "
date -Iminutes
sleep "$@"
sound_alarm

