#!/bin/sh

# XXX NB Don't run commands on the whole file : when running less
# on big files, commands (e.g. grep) can run very long
FORMATTER=256
if [ "$DISPLAY" != "" ]
then
    FORMATTER=terminal256
else
    FORMATTER=terminal
fi

case "$1" in
    *.hs|*.html|*.htm|*.css|\
    *.awk|*.groff|*.java|*.js|*.m4|*.php|*.pl|*.pm|*.pod|*.sh|\
    *.ad[asb]|*.asm|*.inc|*.[ch]|*.[ch]pp|*.[ch]xx|*.cc|*.hh|\
    *.lsp|*.l|*.pas|*.p|*.xml|*.xps|*.xsl|*.axp|*.ppd|*.pov|\
    *.diff|*.patch|*.py|*.rb|*.sql|*.ebuild|*.eclass)
        pygmentize -f $FORMATTER "$1"
        ;;
    .bash*) #.bashrc|.bash_aliases|.bash_environment)
        pygmentize -f $FORMATTER -l sh "$1"
        ;;
    *syslog*)
        pygmentize -f $FORMATTER -l logtalk "$1"
        ;;
    *)
        # check first line for shabang
        grep "#\!/bin/bash" <(head -n 1 "$1") > /dev/null
        if [ "$?" -eq "0" ]; then
            pygmentize -f "${FORMATTER}" -l sh "$1"
        else
            exit 1
        fi
esac

exit 0

# Look up LESS in .bashrc

