#!/bin/bash

# PPPoE and LAN control

set -u
set -e

function usage
{
    echo -e "
Usage: net.sh [COMMAND]
Commands:
    restart : restart pppoe
    up      : start pppoe
    down : stop pppoe
    eth0 : restart connection to LAN
	ping
	lping
"
}

PROV='dsl-provider'

function up
{
    pon "${PROV}"
}

function down
{
    if ! sudo poff -a
    then
        echo "poff error"
    fi
}

function one_check
{
    route -n
}

function check
{
	# default value 3
    watch -g -d -n ${1:-3} route -n
    one_check
}

function restart_eth
{
    sudo ifdown ens5f5
    one_check
    sudo ifup ens5f5
    one_check
}

if [ $# -gt 0 ]; then
    case "$1" in
    "ping" )
        ping -c 10 ya.ru
        ;;
	"lping" )
		ping -c 10 '192.168.0.3'
		;;
    "restart" )
        down
        sleep 5s
        up
        ;;
    "up" )
        up
        sleep 5s
        one_check
        ;;
    "down" )
        down
        sleep 1s
        one_check
        ;;
    "eth0" )
        restart_eth
        ;;
    "check" )
        one_check
        ;;
    "watch" )
		shift # discard 'watch' parameter
        check "$@"
        ;;
    "aw" ) # resetting eth0 and pppoe
        down
        sleep 5s
        one_check
        sleep 1s
        restart_eth
        one_check
        sleep 5s
        up
        check
        ;;
     * )
        usage
        one_check
        ;;
    esac
else
    # TODO add automatic check if pppoe is up
    up
fi

